# Generated by Django 6.0.7 on 2026-09-01 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='usuarios_seguidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
